version: "3.8"

services:
  core:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.1.1-devel-ubuntu22.04
        - PYTHON_VERSION=3.11
        - PROJECT_NAME=accelerator
        - USER_NAME=wajin
        - GROUP_NAME=wajin
        - UID=1000
        - GID=1000
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
      - ../../:/home/wajin/accelerator